name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-format:
    name: Check format

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run format-check

  check-lint:
    name: Check lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run lint-check

  test-code:
    name: Test code

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  test-action: # make sure the action works on a clean machine without building
    name: Test action

    runs-on: ubuntu-latest

    steps:
      - uses: ./

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run package
